src/Entity/Repas.php
<?php

namespace App\Entity;

use App\Repository\RepasRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RepasRepository::class)
 */
class Repas
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $biberon;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantite_ml;

    /**
     * @ORM\Column(type="boolean")
     */
    private $puree;

    /**
     * @ORM\Column(type="boolean")
     */
    private $compote;

    /**
     * @ORM\Column(type="boolean")
     */
    private $yaourt;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantite_pot;

    /**
     * @ORM\OneToMany(targetEntity=Evenement::class, mappedBy="repas")
     */
    private $evenements;

    public function __construct()
    {
        $this->evenements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBiberon(): ?bool
    {
        return $this->biberon;
    }

    public function setBiberon(bool $biberon): self
    {
        $this->biberon = $biberon;

        return $this;
    }

    public function getQuantiteMl(): ?int
    {
        return $this->quantite_ml;
    }

    public function setQuantiteMl(?int $quantite_ml): self
    {
        $this->quantite_ml = $quantite_ml;

        return $this;
    }

    public function getPuree(): ?bool
    {
        return $this->puree;
    }

    public function setPuree(bool $puree): self
    {
        $this->puree = $puree;

        return $this;
    }

    public function getCompote(): ?bool
    {
        return $this->compote;
    }

    public function setCompote(bool $compote): self
    {
        $this->compote = $compote;

        return $this;
    }

    public function getYaourt(): ?bool
    {
        return $this->yaourt;
    }

    public function setYaourt(bool $yaourt): self
    {
        $this->yaourt = $yaourt;

        return $this;
    }

    public function getQuantitePot(): ?int
    {
        return $this->quantite_pot;
    }

    public function setQuantitePot(?int $quantite_pot): self
    {
        $this->quantite_pot = $quantite_pot;

        return $this;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setRepas($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->removeElement($evenement)) {
            // set the owning side to null (unless already changed)
            if ($evenement->getRepas() === $this) {
                $evenement->setRepas(null);
            }
        }

        return $this;
    }
}

src/Form/RepasType.php
<?php

namespace App\Form;

use App\Entity\Repas;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RepasType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('biberon')
            ->add('quantite_ml', TextType::class, [
                "label" => "Quantité (ml)",
                "required" => false
            ])
            ->add('puree')
            ->add('compote')
            ->add('yaourt')
            ->add('quantite_pot')
            // ->add('enregistrer', SubmitType::class, [
            //     "attr" => [
            //         "class" => "btn btn-primary"
            //     ]
            // ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Repas::class,
        ]);
    }
}

src/Controller/RepasController.php
<?php

namespace App\Controller;

use App\Entity\Bebe;
use App\Entity\Evenement;
use App\Entity\Repas;
use App\Form\RepasType;
use App\Repository\BebeRepository;
use App\Repository\ConseilRepository;
use App\Repository\RepasRepository;
use App\Repository\UserRepository;
use App\Repository\UtilisateurRepository;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @Route("/repas")
 */
class RepasController extends AbstractController
{
    /**
     * @Route("/", name="repas_index", methods={"GET"})
     */
    // public function index(RepasRepository $repasRepository): Response
    // {
    //     return $this->render('repas/index.html.twig', [
    //         'repas' => $repasRepository->findAll(),
    //     ]);
    // }

    /**
     * @Route("/ajouter", name="repas_new", methods={"GET","POST"})
     */
    public function new(Request $request, ConseilRepository $conseilRepo): Response
    {
        // Récupération des conseils
        $conseilsBiberon = $conseilRepo->findBy([
            'nom' => "Autour du biberon"
        ]);

        $conseilsDivers = $conseilRepo->findBy([
            'nom' => "Diversification"
        ]);

        $repa = new Repas();
        $form = $this->createForm(RepasType::class, $repa);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            // création d'évènement et le lier au repas
            $event = new Evenement();
            // getUser info de la session
            $utilisateur = $this->getUser();

            $bebe = $utilisateur->getBebe();

            // Convertir la date et la mettre à l'heure française dans le fichier twig.yaml
            $date = new \DateTime('now');
            
            // Remplir l'instance event avec tous les champs évènement :
            $event
                ->setUser($utilisateur)
                ->setBebe($bebe)
                ->setRepas($repa)
                ->setDodo(false)
                ->setHeureDebut($date)
                // ->setHygiene() //pas besoin car il peut être NULL
                // ->setHeureFin() //pas besoin car il peut être NULL  
            ;
          
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($repa);
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('repas/new.html.twig', [
            'repa' => $repa,
            'conseilsBiberon' => $conseilsBiberon,
            'conseilsDivers' => $conseilsDivers,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="repas_show", methods={"GET"})
     */
    public function show(Repas $repa): Response
    {
        return $this->render('repas/show.html.twig', [
            'repa' => $repa,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="repas_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Repas $repa): Response
    {
        $form = $this->createForm(RepasType::class, $repa);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('repas_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('repas/edit.html.twig', [
            'repa' => $repa,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="repas_delete", methods={"POST"})
     */
    public function delete(Request $request, Repas $repa): Response
    {
        if ($this->isCsrfTokenValid('delete'.$repa->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($repa);
            $entityManager->flush();
        }

        return $this->redirectToRoute('repas_index', [], Response::HTTP_SEE_OTHER);
    }
}


 

templates/repas/_delete_form.html.twig
<form method="post" action="{{ path('repas_delete', {'id': repa.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ repa.id) }}">
    <button class="btn">Delete</button>
</form>

templates/repas/_form.html.twig
{% extends "layout.html.twig" %}

{% block content %}
<div class="container">
    <div class="mb-5 retour-accueil">
        <a href="{{path('evenement_index')}}"><i class="fas fa-arrow-left"></i> Retour à la page d'accueil</a>
    </div>  

    <h2>Gestion des repas</h2>
    {{ form_start(form) }}

    <div class="event-section row d-flex flex-row justify-content-center mb-5 pt-5 pb-5">

        {# Biberon #}
        <div class="col-md-4 col-12 me-3 mb-2 color-table">
            <h6 class="text-center mt-2">Biberon</h6>
                <table class="table text-center">
                <tbody>
                        <tr>
                            <td>{{ form_widget(form.biberon) }}</td>    
                        </tr>
                        <tr>
                            <td>Quantité (en ml) :{{ form_widget(form.quantite_ml) }}</td>
                        </tr>
                </tbody>
                </table>
        </div>
        {# Diversification #}
        <div class="col-md-5 col-12 me-3 mb-2 color-table">
            <h6 class="text-center mt-2">Diversification</h6>
                <table class="table text-center">
                <tbody>
                        <tr>
                            <td>{{ form_widget(form.puree) }}</td>  
                            <td>{{ form_widget(form.compote) }}</td> 
                            <td>{{ form_widget(form.yaourt) }}</td>   
                        </tr>
                
                            <td>Quantité (en pot) : {{ form_widget(form.quantite_pot) }}</td>
            
                </tbody>
                </table>
        </div>
        {% if is_granted("IS_AUTHENTICATED_FULLY") %}
        <div class="row">
            <div class="offset-1 col-2 mt-4">
                <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
            </div>
        </div>
        {% else %}
        <div class="alert alert-info m-3" role="alert">
            Authentifiez-vous pour rentrer les informations de bébé  <a class="underline" href="{{path('user_new')}}"> Inscrivez-vous</a> ou
            <a href="{{path('app_login')}}"> Connectez-vous</a> 
        </div> 
        {% endif %}
        {# Fin de la row #}
        </div>

            

    {{ form_end(form) }}

    {# information #}
        <h2>Conseils autour de bébé</h2>
        <div class="section-info">
        
            <div class="row d-flex section-info justify-content-center pt-4 pb-4 mb-5">
                <div class="col-md-3 col-3">
                    <img class="me-2 w-75" src="{{ asset('image/repas/biberon2.jpg')}}" alt="rust-texture">
                </div>
                <div class="col-md-9 col-12">

                {% for conseil in conseilsBiberon %}
                    <h4>{{conseil.nom}}</h4>
                    <p>{{conseil.description}}}}</p>
                {% endfor %}
                        
                </div>
            </div>

            <div class="row section-info pb-4 ps-4 pe-4 mb-5">
               
                <div class="col-md-9 col-12">
                {% for conseil in conseilsDivers %}
                    <h4>{{conseil.nom}}</h4>
                    <p>{{conseil.description}}</p>
                {% endfor %}
                </div>
                 <div class="col-md-3 col-3">
                    <img class="me-2" src="{{ asset('image/repas/diversification3.jpg')}}" alt="rust-texture">
                </div>
            </div>


        </div>

{# Fin div container #}
</div>
{% endblock %}

templates/repas/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Repas{% endblock %}

{% block body %}
    <h1>Edit Repas</h1>

    {{ include('repas/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('repas_index') }}">back to list</a>

    {{ include('repas/_delete_form.html.twig') }}
{% endblock %}

templates/repas/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Repas index{% endblock %}

{% block body %}
    <h1>Repas index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Biberon</th>
                <th>Quantite_ml</th>
                <th>Puree</th>
                <th>Compote</th>
                <th>Yaourt</th>
                <th>Quantite_pot</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for repa in repas %}
            <tr>
                <td>{{ repa.id }}</td>
                <td>{{ repa.biberon ? 'Yes' : 'No' }}</td>
                <td>{{ repa.quantiteMl }}</td>
                <td>{{ repa.puree ? 'Yes' : 'No' }}</td>
                <td>{{ repa.compote ? 'Yes' : 'No' }}</td>
                <td>{{ repa.yaourt ? 'Yes' : 'No' }}</td>
                <td>{{ repa.quantitePot }}</td>
                <td>
                    <a href="{{ path('repas_show', {'id': repa.id}) }}">show</a>
                    <a href="{{ path('repas_edit', {'id': repa.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('repas_new') }}">Create new</a>
{% endblock %}

templates/repas/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{parent()}}{% endblock %}

{% block body %}
    {{ include('repas/_form.html.twig') }}
{% endblock %}

templates/repas/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Repas{% endblock %}

{% block body %}
    <h1>Repas</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ repa.id }}</td>
            </tr>
            <tr>
                <th>Biberon</th>
                <td>{{ repa.biberon ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Quantite_ml</th>
                <td>{{ repa.quantiteMl }}</td>
            </tr>
            <tr>
                <th>Puree</th>
                <td>{{ repa.puree ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Compote</th>
                <td>{{ repa.compote ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Yaourt</th>
                <td>{{ repa.yaourt ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Quantite_pot</th>
                <td>{{ repa.quantitePot }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('repas_index') }}">back to list</a>

    <a href="{{ path('repas_edit', {'id': repa.id}) }}">edit</a>

    {{ include('repas/_delete_form.html.twig') }}
{% endblock %}