src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvenementRepository::class)
 */
class Evenement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="evenements")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Bebe::class, inversedBy="evenements")
     * @ORM\JoinColumn(nullable=false)
     */
    private $bebe;

    /**
     * @ORM\ManyToOne(targetEntity=Repas::class, inversedBy="evenements")
     * @ORM\JoinColumn(nullable=true)
     */
    private $repas;

    /**
     * @ORM\ManyToOne(targetEntity=Hygiene::class, inversedBy="evenements")
     * @ORM\JoinColumn(nullable=true)
     */
    private $hygiene;

    /**
     * @ORM\Column(type="boolean")
     */
    private $dodo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $heure_debut;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $heure_fin;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBebe(): ?Bebe
    {
        return $this->bebe;
    }

    public function setBebe(?Bebe $bebe): self
    {
        $this->bebe = $bebe;

        return $this;
    }

    public function getRepas(): ?Repas
    {
        return $this->repas;
    }

    public function setRepas(?Repas $repas): self
    {
        $this->repas = $repas;

        return $this;
    }

    public function getHygiene(): ?Hygiene
    {
        return $this->hygiene;
    }

    public function setHygiene(?Hygiene $hygiene): self
    {
        $this->hygiene = $hygiene;

        return $this;
    }

    public function getDodo(): ?bool
    {
        return $this->dodo;
    }

    public function setDodo(bool $dodo): self
    {
        $this->dodo = $dodo;

        return $this;
    }

    public function getHeureDebut(): ?\DateTimeInterface
    {
        return $this->heure_debut;
    }

    public function setHeureDebut(\DateTimeInterface $heure_debut): self
    {
        $this->heure_debut = $heure_debut;

        return $this;
    }

    public function getHeureFin(): ?\DateTimeInterface
    {
        return $this->heure_fin;
    }

    public function setHeureFin(?\DateTimeInterface $heure_fin): self
    {
        $this->heure_fin = $heure_fin;

        return $this;
    }
}

src/Entity/Hygiene.php
<?php

namespace App\Entity;

use App\Repository\HygieneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HygieneRepository::class)
 */
class Hygiene
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $couche_urine;

    /**
     * @ORM\Column(type="boolean")
     */
    private $couche_selle;

    /**
     * @ORM\Column(type="boolean")
     */
    private $bain;

    /**
     * @ORM\OneToMany(targetEntity=Evenement::class, mappedBy="hygiene")
     */
    private $evenements;

    public function __construct()
    {
        $this->evenements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCoucheUrine(): ?bool
    {
        return $this->couche_urine;
    }

    public function setCoucheUrine(bool $couche_urine): self
    {
        $this->couche_urine = $couche_urine;

        return $this;
    }

    public function getCoucheSelle(): ?bool
    {
        return $this->couche_selle;
    }

    public function setCoucheSelle(bool $couche_selle): self
    {
        $this->couche_selle = $couche_selle;

        return $this;
    }

    public function getBain(): ?bool
    {
        return $this->bain;
    }

    public function setBain(bool $bain): self
    {
        $this->bain = $bain;

        return $this;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setHygiene($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->removeElement($evenement)) {
            // set the owning side to null (unless already changed)
            if ($evenement->getHygiene() === $this) {
                $evenement->setHygiene(null);
            }
        }

        return $this;
    }
}

src/Entity/Repas.php
<?php

namespace App\Entity;

use App\Repository\RepasRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RepasRepository::class)
 */
class Repas
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $biberon;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantite_ml;

    /**
     * @ORM\Column(type="boolean")
     */
    private $puree;

    /**
     * @ORM\Column(type="boolean")
     */
    private $compote;

    /**
     * @ORM\Column(type="boolean")
     */
    private $yaourt;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantite_pot;

    /**
     * @ORM\OneToMany(targetEntity=Evenement::class, mappedBy="repas")
     */
    private $evenements;

    public function __construct()
    {
        $this->evenements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBiberon(): ?bool
    {
        return $this->biberon;
    }

    public function setBiberon(bool $biberon): self
    {
        $this->biberon = $biberon;

        return $this;
    }

    public function getQuantiteMl(): ?int
    {
        return $this->quantite_ml;
    }

    public function setQuantiteMl(?int $quantite_ml): self
    {
        $this->quantite_ml = $quantite_ml;

        return $this;
    }

    public function getPuree(): ?bool
    {
        return $this->puree;
    }

    public function setPuree(bool $puree): self
    {
        $this->puree = $puree;

        return $this;
    }

    public function getCompote(): ?bool
    {
        return $this->compote;
    }

    public function setCompote(bool $compote): self
    {
        $this->compote = $compote;

        return $this;
    }

    public function getYaourt(): ?bool
    {
        return $this->yaourt;
    }

    public function setYaourt(bool $yaourt): self
    {
        $this->yaourt = $yaourt;

        return $this;
    }

    public function getQuantitePot(): ?int
    {
        return $this->quantite_pot;
    }

    public function setQuantitePot(?int $quantite_pot): self
    {
        $this->quantite_pot = $quantite_pot;

        return $this;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setRepas($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->removeElement($evenement)) {
            // set the owning side to null (unless already changed)
            if ($evenement->getRepas() === $this) {
                $evenement->setRepas(null);
            }
        }

        return $this;
    }
}

src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Evenement;
use App\Entity\Hygiene;
use App\Entity\Repas;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            // ->add('heure_debut', TimeType::class, [
            //     "widget" => "single_text",
            //     'view_timezone'  => 'Europe/Paris'
            //     ])
            ->add('heure_fin', TimeType::class, [
                "widget" => "single_text",
                'view_timezone'  => 'Europe/Paris'
            ])
            ->add('dodo')

            // ->add('enregistrer', SubmitType::class, [
            //     "attr" => [
            //         "class" => "btn btn-primary"
            //     ]
            // ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,
        ]);
    }
}

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\ConseilRepository;
use App\Repository\EvenementRepository;
use App\Repository\UserRepository;
use App\Service\CallApiService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/accueil")
 */
class EvenementController extends AbstractController
{
    
    /**
     * @Route("/", name="evenement_index", methods={"GET"})
     */
    public function index(EvenementRepository $evenementRepository, ConseilRepository $conseilRepo): Response
    {
        
        // récupération des conseils
        $conseils = $conseilRepo->findBy([
            'nom' => "Conseil d'été !"
        ]);

        $isToday = false;
        
        //récupération de l'utilisateur
        $utilisateur = $this->getUser();

        $dateNow = new \DateTime('now');
        
        if($utilisateur) {
            $bebe = $utilisateur->getBebe();
        } else {  
            $bebe = "mumu"; // bébé existant en BDD 
        }
       
        $elements = $evenementRepository->findBy([
            'bebe' => $bebe
        ]);

        // comparaison de la date d'insert avec la date actuelle
        foreach($elements as $element) {
            // Extraction du jour et mois :
            $dateElement = $element->getHeureDebut();
            $dateConvert = $dateElement->format('Y-m-d');

            $dateNowConvert = $dateNow->format('Y-m-d');
            
            if($dateConvert == $dateNowConvert) {
                $isToday = true;
            }
        }
        return $this->render('evenement/index.html.twig', [
            'evenements' => $elements,
            'isToday' => $isToday,
            'conseils' => $conseils,
        ]);
    }

    /**
     * @Route("/new", name="evenement_new", methods={"GET","POST"})
     */
    /**
     * @Route("/sommeil/ajouter", name="evenement_sommeil", methods={"GET","POST"})
     */
    public function new(Request $request, ConseilRepository $conseilRepo): Response
    {
        // récupération des conseils
        $conseils = $conseilRepo->findBy([
            'nom' => "Quand fera t-il ses nuits ?"
        ]);

        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
           
              // getUser info de la session :
              $utilisateur = $this->getUser();
  
              $bebe = $utilisateur->getBebe();
              $date = new \DateTime('now');

              // Remplir l'instance event avec tous les champs évènement :
              $evenement
                  ->setUser($utilisateur)
                  ->setBebe($bebe)
                  ->setHeureDebut($date)
                ;

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($evenement);
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('evenement/new.html.twig', [
            'evenement' => $evenement,
            'conseils' => $conseils,
            'form' => $form,

        ]);
    }

    /**
     * @Route("/{id}", name="evenement_show", methods={"GET"})
     */
    public function show(Evenement $evenement): Response
    {
        return $this->render('evenement/show.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="evenement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Evenement $evenement): Response
    {
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="evenement_delete", methods={"POST"})
     */
    public function delete(Request $request, Evenement $evenement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($evenement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/evenement/_delete_form.html.twig
<form method="post" action="{{ path('evenement_delete', {'id': evenement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evenement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/evenement/_form.html.twig
{% extends "layout.html.twig" %}

{% block content %}
<div class="container">
    <div class="mb-5">
        <a href="{{path('evenement_index')}}"><i class="fas fa-arrow-left"></i> Retour à la page d'accueil</a>
    </div>  
   
<h2>Gestion du sommeil</h2>
{{ form_start(form) }}
  <div class="event-section row d-flex justify-content-center mb-5">

    {# Sommeil #}
    <div class="col-md-3 col-10 mb-2 me-3 color-table">
        <h6 class="text-center mt-2">Sommeil</h6>
            <table class="table text-center">
            <tbody>
                    <tr>
                         <td>{{ form_widget(form.dodo, {
                            'label': 'Bébé dort'}) }}</td>    
                    </tr>
            </tbody>
            </table>
    </div>

    {# heure_fin #}
    <div class="col-md-3 col-10 me-3 mb-2 color-table">
        <h6 class="text-center mt-2">Heure de fin</h6>
            <table class="table text-center">
            <tbody>
                    <tr>
                         <td>{{ form_widget(form.heure_fin) }}</td>    
                    </tr>
            </tbody>
            </table>
    </div>

   {% if is_granted("IS_AUTHENTICATED_FULLY") %}
        <div class="row">
            <div class="offset-md-2 col-2 mt-4 mb-4">
                <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
            </div>
        </div>
        {% else %}
        <div class="alert alert-info m-3" role="alert">
            Authentifiez-vous pour rentrer les informations de bébé  <a class="underline" href="{{path('user_new')}}"> Inscrivez-vous</a> ou
            <a href="{{path('app_login')}}"> Connectez-vous</a> 
        </div> 
        {% endif %}
</div> 
{{ form_end(form) }}


{# information #}
        <h2>Conseils autour de bébé</h2>
        <div class="section-info d-flex row pt-4 pb-4 mb-5">
            <div class="col-md-3 col-3">
                <img class="me-2" src="{{ asset('image/dodo/photo-dodo1.jpg')}}" alt="rust-texture">
            </div>
            <div class="col-md-9 col-12">

            {% for conseil in conseils %}
                <h4>{{conseil.nom}}</h4>
                <p>{{conseil.description}}</p>
            {% endfor %}
            </div>
        </div> 
</div>


{% endblock %}

templates/evenement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Evenement{% endblock %}

{% block body %}
    <h1>Edit Evenement</h1>

    {{ include('evenement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('evenement_index') }}">back to list</a>

    {{ include('evenement/_delete_form.html.twig') }}
{% endblock %}

templates/evenement/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{parent()}}{% endblock %}

{% block content %}
    <h1>Un coup de pouce pour les parents</h1>
    <p class="mb-5">L'enfantDo est fait pour vous aider dans les tâches qui concerne votre bébé. Grâce à la gestion de bébé, vous pouvez voir toutes les informations qui concerne bébé et ainsi <span class="gras">mieux vous organiser.</span> <br>
    Vous savez ainsi où en est bébé dans les repas, le changement des couches, du bain et du sommeil. <br>
    Vous pouvez aussi inscrire une autre personne qui s'occupe de bébé et ainsi mieux vous répartir les tâches!
    </p>
   
    <h2>Gestion de bébé</h2>
    <h6 class="mt-4">{{ "now" | date('d/m/Y à H:i', "Europe/Paris" ) }}</h6>

   
    {% if is_granted("IS_AUTHENTICATED_FULLY") %}
        
    <div class="event-section row d-flex justify-content-center mb-5 pt-4 pb-4">
    {# edition #}
        <div class="col-md-1">
        </div>
        {# Tableau heure #}
        <div class="col-md-1 me-3 col-3 mb-2 base">
        <h6 class="text-center mt-2">Heure</h6>
            <table class="table text-center">
            <thead>
                <tr>
                    <th>Début</th>
                </tr>
            </thead>
            <tbody>
                {% for evenement in evenements %}
                    {% if evenement.heureDebut|date('d/m/Y') == "now" | date('d/m/Y', "Europe/Paris" ) %}      
                    <tr>
                         <td>{{ evenement.heureDebut ? evenement.heureDebut|date('H:i') : '' }}</td>    
                    </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
                
            </table>
        </div>

    {# Tableau repas #}
        {# Tableau biberon #}
        <div class="col-md-1 me-3 col-7 mb-2 color-table">
        <h6 class="text-center mt-2">Biberon</h6>
            <table class="table text-center">
            <thead>
                <tr>
                    <th>Quantité</th>
                </tr>
            </thead>
            <tbody>
                {% for evenement in evenements %}
                    {% if evenement.heureDebut|date('d/m/Y') == "now" | date('d/m/Y', "Europe/Paris" ) %}  
                    <tr>
                        <td>
                        {% if evenement.repas is null %}
                            <i class="far fa-clock"></i>
                        {% else %}
                        {{evenement.repas.quantiteMl ? evenement.repas.quantiteMl : '-'}}
                        {% endif %}
                        
                        </td>
                    </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
                
            </table>
        </div>
        {# Tableau diversification #}
        <div class="col-md-3 col-6 me-3 mb-2 color-table">
        <h6 class="text-center mt-2">Diversification</h6>
            <table class="table text-center">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Quantité (pot)</th>
                </tr>
            </thead>
            <tbody>
                {% for evenement in evenements %}
                    {% if evenement.heureDebut|date('d/m/Y') == "now" | date('d/m/Y', "Europe/Paris" ) %}  
                    <tr>
                        <td>
                        {% if evenement.repas is null %}
                            <i class="far fa-clock"></i>
                        {% elseif evenement.repas.puree %}
                            Purée
                        {% elseif evenement.repas.compote %}
                            Compote
                        {% elseif evenement.repas.Yaourt %}
                            Yaourt
                        {% else %}
                            <i class="far fa-clock"></i>
                        {% endif %}
                        </td>
                        <td>
                        {% if evenement.repas is null %}
                            <i class="far fa-clock"></i>
                        {% elseif evenement.repas.quantitepot %}
                             {{evenement.repas.quantitepot}}
                        {% else %}
                            <i class="far fa-clock"></i>
                        {% endif %}
                        </td>
                    </tr>
                    {% endif %}
                {% endfor %}
            </tbody>   
            </table>
        </div>
        {# Tableau hygiène #}
        <div class="col-md-1 me-3 mb-2 col-4 color-table">
        <h6 class="text-center mt-2">Couche</h6>
            <table class="table text-center">
            <thead>
                <tr>
                    <th>Type</th>
                </tr>
            </thead>
            <tbody>
                {% for evenement in evenements %}
                    {% if evenement.heureDebut|date('d/m/Y') == "now" | date('d/m/Y', "Europe/Paris" ) %}  
                    <tr>
                        <td>
                        {% if evenement.hygiene is null %}
                             <i class="far fa-clock"></i>
                        {% elseif evenement.hygiene.coucheUrine %}
                            Urine
                        {% elseif evenement.hygiene.coucheSelle %}
                            Selle
                        {% else %}
                            <i class="far fa-clock"></i>
                        {% endif %} 
                        </td>
                    </tr>
                    {% endif %}
                {% endfor %}
            </tbody>   
            </table>
        </div>
        {# Tableau bain #}
        <div class="col-md-1 me-3 mb-2 col-4 color-table">
        <h6 class="text-center mt-2">Bain</h6>
            <table class="table text-center">
            <thead>
                <tr>
                    <th>Prise</th>
                </tr>
            </thead>
            <tbody>
               {% for evenement in evenements %}
                    {% if evenement.heureDebut|date('d/m/Y') == "now" | date('d/m/Y', "Europe/Paris" ) %}  
                    <tr>
                        <td>
                        {% if evenement.hygiene is null %}
                            <i class="far fa-clock"></i>
                        {% elseif evenement.hygiene.bain %}
                            <i class="fas fa-check"></i>

                        {% else %}
                            <i class="far fa-clock"></i>
                        {% endif %} 
                        </td>
                    </tr>
                    {% endif %}
                {% endfor %}
            </tbody>   
            </table>
        </div>
        {# Tableau dodo #}
        <div class="col-md-2 me-3 mb-2 col-6 color-table">
        <h6 class="text-center mt-2">Sommeil</h6>
            <table class="table text-center">
            <thead>
                <tr>
                    <th>Début</th>
                    <th>Fin</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for evenement in evenements %}
                    {% if evenement.heureDebut|date('d/m/Y') == "now" | date('d/m/Y', "Europe/Paris" ) %}  
                    <tr>
                        <td>
                            {% if evenement.dodo %}
                                <i class="fas fa-check"></i>
                            {% else %}
                                <i class="far fa-clock"></i>
                            {% endif %}
                        </td> 
                        <td>
                            {% if evenement.heureFin %}
                                {{evenement.heureFin|date('H:i')}}
                            {% else %}
                                <i class="far fa-clock"></i>
                            {% endif %}
                        </td>
                        <td><a href="{{ path('evenement_edit', {'id': evenement.id}) }}"><i class="fas fa-feather"></i></a></td>
                    </tr>
                    {% endif %}
                {% endfor %}
            </tbody>   
            </table>
        </div>
    
    {# end div row #}
    </div> 
 
    {% else %}
    <div class="alert alert-info text-center mt-5 mb-5" role="alert">
    <p>Pour profiter des fonctionnalités de l'Enfant Do, veuillez-vous authentifier</p>
    <a class="underline" href="{{path('user_new')}}">Inscrivez-vous</a> ou
    <a href="{{path('app_login')}}">Connectez-vous</a> 
   </div>
{% endif %}

    {# urgence #}
     <div class="mb-5">
        <h2>Une urgence ?</h2>
        <p>Vous avez un doute sur le comportement de bébé. Ne cherchez pas suivez le lien pour voir la liste des hopitaux :</p>
        <a href="{{path('soin_liste')}}">Voir la liste des hopitaux</a>
    </div>

    

    {# information #}
    <h2>Conseils autour de bébé</h2>
    <div class="section-info row d-flex pt-4 pb-4 mb-5">
        <div class="col-md-3 col-3">
            <img class="me-2" src="{{ asset('image/dodo/photo-dodo2.jpg')}}" alt="rust-texture">
        </div>
        <div class="col-md-9 col-12">
        {% for conseil in conseils %}
            <h4>{{conseil.nom}}</h4>
            <p>{{conseil.description}}</p>
        {% endfor %}
        </div>
    </div>
             
           


    
                    {# <a href="{{ path('evenement_show', {'id': evenement.id}) }}">show</a>
                    <a href="{{ path('evenement_edit', {'id': evenement.id}) }}">edit</a> #}
           

    {# <a href="{{ path('evenement_new') }}">Create new</a> #}
{% endblock %}

templates/evenement/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{parent()}}{% endblock %}

{% block body %}

    {{ include('evenement/_form.html.twig') }}

    {# <a href="{{ path('evenement_index') }}">back to list</a> #}
{% endblock %}

templates/evenement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}
    <h1>Evenement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ evenement.id }}</td>
            </tr>
            <tr>
                <th>Dodo</th>
                <td>{{ evenement.dodo ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Heure_debut</th>
                <td>{{ evenement.heureDebut ? evenement.heureDebut|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Heure_fin</th>
                <td>{{ evenement.heureFin ? evenement.heureFin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('evenement_index') }}">back to list</a>

    <a href="{{ path('evenement_edit', {'id': evenement.id}) }}">edit</a>

    {{ include('evenement/_delete_form.html.twig') }}
{% endblock %}